[build]
  functions = "netlify/functions"
  command = "npm run build" # Adjust based on your build command
  publish = "build"         # Adjust based on your build output directory

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
